#!/command/with-contenv bash

source /assets/functions/00-container
source /assets/defaults/kopano-global
source /assets/functions/kopano

PROCESS_NAME="kopano-search"
check_container_initialized
liftoff

rm -rf /var/run/kopano/search.pid

wait_for_server search
sleep 3

case "${KC_BASE}" in
    8.7.* )
        version_args="-F"
    ;;
    10.*|11.*)
        :
    ;;
esac

print_start "Starting Kopano Search"
exec kopano-search "${SEARCH_ADDITIONAL_ARGS}" "${version_args}"
