#!/command/with-contenv bash

source /assets/functions/00-container
source /assets/functions/kopano
source /assets/defaults/kopano-global
prepare_service both

PROCESS_NAME="kopano-prometheus-exporter"
check_container_initialized
liftoff

wait_for_server server
print_start "Starting Kopano Prometheus Exporter $(/usr/sbin/prometheus-kopano-exporter version | head -n1 | awk '{print $3}')"
exec sudo -u kopano /usr/sbin/prometheus-kopano-exporter \
                serve \
                --listen-address $(cat ${CONFIG_PATH}/prometheus_exporter.cfg | grep "listen =" | awk '{print $3}') \
                --listen-socket $(cat ${CONFIG_PATH}/prometheus_exporter.cfg | grep "socket =" | awk '{print $3}' | sed "s|unix:||g" ) \
                --log-level $(cat ${CONFIG_PATH}/prometheus_exporter.cfg | grep "log_level =" | awk '{print $3}') >> ${LOG_PATH_KOPANO}/${LOG_FILE_PROMETHEUS_EXPORTER} 2>&1