#!/command/with-contenv bash

source /assets/functions/00-container
source /assets/defaults/kopano-global
source /assets/functions/kopano

PROCESS_NAME="kopano-ical"
check_container_initialized
liftoff

wait_for_server ical
sleep 3

case "${KC_BASE}" in
    8.7.* )
        version_args="-F"
    ;;
    10.*|11.*)
        :
    ;;
esac

print_start "Starting Kopano ICAL Server"
kopano-ical "${ICAL_ADDITIONAL_ARGS}" "${version_args}"
