#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service functions kopano

PROCESS_NAME="kopano-server"
check_container_initialized
liftoff

rm -rf /var/run/kopano/server.pid

case "${KC_BASE}" in
    8.7.* )
        version_args="-F"
    ;;
    10.*|11.*)
        :
    ;;
esac

print_start "Starting Kopano Server"
kopano-server "${SERVER_ADDITIONAL_ARGS}" "${version_args}"
