#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service functions kopano

PROCESS_NAME="kopano-server"
check_container_initialized
liftoff

rm -rf /var/run/kopano/spooler.pid

wait_for_server spooler
sleep 3

case "${KC_BASE}" in
    8.7.* )
        version_args="-F"
    ;;
    10.*|11.*)
        :
    ;;
esac

print_start "Starting Kopano Spooler"
kopano-spooler "${version_args}"
