#!/command/with-contenv bash

source /assets/functions/00-container
source /assets/defaults/kopano-global
source /assets/functions/kopano

PROCESS_NAME="kopano-spamd"
check_container_initialized
liftoff

rm -rf /var/run/kopano/spamd.pid

wait_for_server spamd
sleep 3

case "${KC_BASE}" in
    8.7.* )
        version_args="-F"
    ;;
    10.*|11.*)
        :
    ;;
esac

print_start "Starting Kopano Spamd Service"
exec kopano-spamd "${SPAMD_ADDITIONAL_ARGS}" "${version_args}"
