#!/command/with-contenv bash

source /assets/functions/00-container
source /assets/defaults/kopano-global
source /assets/functions/kopano

PROCESS_NAME="kopano-monitor"
check_container_initialized
liftoff

rm -rf /var/run/kopano/monitor.pid

wait_for_server monitor
sleep 3

case "${KC_BASE}" in
    8.7.* )
        version_args="-F"
    ;;
    10.*|11.*)
        version_args="-F"
    ;;
esac

print_start "Starting Kopano Monitoring Service"
exec kopano-monitor "${MONITOR_ADDITIONAL_ARGS}" "${version_args}"
