#!/usr/bin/with-contenv bash

source /assets/functions/00-container
source /assets/defaults/kopano-global
source /assets/functions/kopano
setup_container_mode

PROCESS_NAME="kopano-core"

mkdir -p "${CONFIG_PATH}"
configure_logging

### Server Config
if var_true "${ENABLE_SERVER}" ; then
	print_debug "Configuring Kopano Server"
    source /assets/defaults/kopano-server
	source /assets/defaults/kopano-search
	sanity_db
	db_ready mariadb
	create_user_scripts
	configure_cron_purge_deleted
	configure_server
	if [ "${LOG_TYPE}" = "FILE" ] || [ "${LOG_TYPE}" = "file" ] ; then
		create_logrotate kopano-server ${LOG_PATH_KOPANO}/${LOG_FILE_SERVER} kopano-server kopano kopano
	fi
	print_debug "Finished Configuring Kopano Server"
else
	service_stop 31-kopano-server
    service_stop 90-post-server-startup-routines
fi

### Autorespond Config
if var_true "${ENABLE_AUTORESPOND}" ; then
	print_debug "Configuring Autorespond"
	source /assets/defaults/kopano-autorespond
	configure_autorespond
	print_debug "Finished Configuring Autorespond"
fi

### Backup Config
if var_true "${ENABLE_BACKUP}" ; then
	print_debug "Configuring Backup"
	source /assets/defaults/kopano-backup
	configure_backup
	if [ "${LOG_TYPE}" = "FILE" ] || [ "${LOG_TYPE}" = "file" ] ; then
		create_logrotate kopano-backup ${LOG_PATH_KOPANO}/${LOG_FILE_BACKUP} kopano-backup kopano kopano
	fi
	print_debug "Finished Configuring Backup"
fi

### DAgent Config
if var_true "${ENABLE_DAGENT}" ; then
	print_debug "Configuring DAgent"
	source /assets/defaults/kopano-dagent
	configure_dagent
	if [ "${LOG_TYPE}" = "FILE" ] || [ "${LOG_TYPE}" = "file" ] ; then
		create_logrotate kopano-dagent ${LOG_PATH_KOPANO}/${LOG_FILE_DAGENT} kopano-dagent kopano kopano
	fi
	print_debug "Finished Configuring DAgent"
else
	service_stop 34-kopano-dagent
fi

### Gateway Config
if var_true "${ENABLE_GATEWAY}" ; then
	print_debug "Configuring Gateway"
	source /assets/defaults/kopano-gateway
	configure_gateway
	if [ "${LOG_TYPE}" = "FILE" ] || [ "${LOG_TYPE}" = "file" ] ; then
		create_logrotate kopano-gateway ${LOG_PATH_KOPANO}/${LOG_FILE_GATEWAY} kopano-gateway kopano kopano
	fi
	print_debug "Finished Configuring Gateway"
else
    service_stop 33-kopano-gateway
fi

### ICAL Config
if var_true "${ENABLE_ICAL}" ; then
	print_debug "Configuring ICAL"
	source /assets/defaults/kopano-ical
	configure_ical
	if [ "${LOG_TYPE}" = "FILE" ] || [ "${LOG_TYPE}" = "file" ] ; then
		create_logrotate kopano-ical ${LOG_PATH_KOPANO}/${LOG_FILE_ICAL} kopano-ical kopano kopano
	fi
	print_debug "Finished Configuring ICAL"
else
	service_stop 35-kopano-ical
fi

### Monitor Config
if var_true "${ENABLE_MIGRATOR}" ; then
	print_debug "Configuring Migrator"
	source /assets/defaults/kopano-gateway
	configure_migrator
	if [ "${LOG_TYPE}" = "FILE" ] || [ "${LOG_TYPE}" = "file" ] ; then
		create_logrotate kopano-migrator ${LOG_PATH_KOPANO}/${LOG_FILE_MIGRATOR} kopano-gateway kopano kopano
	fi
	print_debug "Finished Configuring Migrator"
else
	service_stop 92-kopano-gateway-migrator
fi

### Monitor Config
if var_true "${ENABLE_MONITOR}" ; then
	print_debug "Configuring Monitor"
	source /assets/defaults/kopano-monitor
	create_quota_templates
	configure_monitor
	if [ "${LOG_TYPE}" = "FILE" ] || [ "${LOG_TYPE}" = "file" ] ; then
		create_logrotate kopano-monitor ${LOG_PATH_KOPANO}/${LOG_FILE_MONITOR} none kopano kopano
	fi
	print_debug "Finished Configuring Monitor"
else
	service_stop 38-kopano-monitor
fi

### Search Config
if var_true "${ENABLE_SEARCH}" ; then
	print_debug "Configuring Search"
	source /assets/defaults/kopano-search
	configure_search
	if [ "${LOG_TYPE}" = "FILE" ] || [ "${LOG_TYPE}" = "file" ] ; then
		create_logrotate kopano-search ${LOG_PATH_KOPANO}/${LOG_FILE_SEARCH} kopano-search kopano kopano
	fi
	print_debug "Finished Configuring Search"
else
	service_stop 37-kopano-search
fi

### SPAMD Config
if var_true "${ENABLE_SPAMD}" ; then
	print_debug "Configuring Spamd"
	source /assets/defaults/kopano-dagent
	source /assets/defaults/kopano-spamd
	configure_spamd
	if [ "${LOG_TYPE}" = "FILE" ] || [ "${LOG_TYPE}" = "file" ] ; then
		create_logrotate kopano-spamd ${LOG_PATH_KOPANO}/${LOG_FILE_SPAMD} kopano-spamd kopano kopano
	fi
	print_debug "Finished Configuring Spamd"
else
	service_stop 36-kopano-spamd
fi

### Spooler Config
if var_true "${ENABLE_SPOOLER}" ; then
	print_debug "Configuring Spooler"
	source /assets/defaults/kopano-spooler
	configure_spooler
	if [ "${LOG_TYPE}" = "FILE" ] || [ "${LOG_TYPE}" = "file" ] ; then
		create_logrotate kopano-spooler ${LOG_PATH_KOPANO}/${LOG_FILE_SPOOLER} kopano-spooler kopano kopano
	fi
	print_debug "Finished Configuring Spooler"
else
	service_stop 32-kopano-spooler
fi

custom_files /assets/custom /
custom_scripts /assets/custom-scripts

liftoff
