#!/command/with-contenv bash

source /assets/functions/00-container
source /assets/defaults/kopano-global
source /assets/functions/kopano

PROCESS_NAME="kopano-gateway"
check_container_initialized
liftoff

rm -rf /var/run/kopano/gateway.pid

wait_for_server gateway
sleep 3

case "${KC_BASE}" in
    8.7.* )
        version_args="-F"
    ;;
    10.*|11.*)
        :
    ;;
esac

print_start "Starting Kopano Gateway"
exec kopano-gateway "${GATEWAY_ADDITIONAL_ARGS}" "${version_args}"
